name: Challenge 1
# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches:
      - main

jobs:
  build:
    name: BuildDocker
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: raknes.azurecr.io
          repository: devopsdaysams
          tags: latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
