name: Challenge 1
# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches:
      - main

jobs:
  build:
    # Job name is PrintURL
    name: PrintURL
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step writes out the full url of your GitHub repo in the log file
      - name: Write repo full URL
        run: echo 'The repo URL is ${{ github.repository }}.'
